__all__ = [
    'FG_BLACK', 'FG_RED', 'FG_GREEN', 'FG_YELLOW', 'FG_BLUE', 'FG_MAGENTA',
    'FG_CYAN', 'FG_WHITE', 'FG_GRAY', 'FG_GRAY_LIGHT', 'FG_RED_LIGHT',
    'FG_GREEN_LIGHT', 'FG_YELLOW_LIGHT', 'FG_BLUE_LIGHT', 'FG_MAGENTA_LIGHT',
    'FG_CYAN_LIGHT', 'BG_BLACK', 'BG_RED', 'BG_GREEN', 'BG_YELLOW', 'BG_BLUE',
    'BG_MAGENTA', 'BG_CYAN', 'BG_WHITE', 'BG_GRAY', 'BG_GRAY_LIGHT',
    'BG_RED_LIGHT', 'BG_GREEN_LIGHT', 'BG_YELLOW_LIGHT', 'BG_BLUE_LIGHT',
    'BG_MAGENTA_LIGHT', 'BG_CYAN_LIGHT', 'FG_BG_CLEAR'
]

# ANSI foreground color codes
FG_BLACK = "\x1B[30m"
FG_RED = "\x1B[31m"
FG_GREEN = "\x1B[32m"
FG_YELLOW = "\x1B[33m"
FG_BLUE = "\x1B[34m"
FG_MAGENTA = "\x1B[35m"
FG_CYAN = "\x1B[36m"
FG_WHITE = "\x1B[37m"
FG_GRAY = "\x1B[90m"
FG_GRAY_LIGHT = "\x1B[37m"
FG_RED_LIGHT = "\x1B[91m"
FG_GREEN_LIGHT = "\x1B[92m"
FG_YELLOW_LIGHT = "\x1B[93m"
FG_BLUE_LIGHT = "\x1B[94m"
FG_MAGENTA_LIGHT = "\x1B[95m"
FG_CYAN_LIGHT = "\x1B[96m"

# ANSI background color codes
BG_BLACK = "\x1B[40m"
BG_RED = "\x1B[41m"
BG_GREEN = "\x1B[42m"
BG_YELLOW = "\x1B[43m"
BG_BLUE = "\x1B[44m"
BG_MAGENTA = "\x1B[45m"
BG_CYAN = "\x1B[46m"
BG_WHITE = "\x1B[47m"
BG_GRAY = "\x1B[100m"
BG_GRAY_LIGHT = "\x1B[47m"
BG_RED_LIGHT = "\x1B[101m"
BG_GREEN_LIGHT = "\x1B[102m"
BG_YELLOW_LIGHT = "\x1B[103m"
BG_BLUE_LIGHT = "\x1B[104m"
BG_MAGENTA_LIGHT = "\x1B[105m"
BG_CYAN_LIGHT = "\x1B[106m"

# Clear
FG_BG_CLEAR = "\x1B[0m"